### PR TITLE
Various compatible changes to support multi-server environment

### PR DESCRIPTION
**Pull request by twinpiloot**
The following changes have been implemented:
- Support for non-default install directories
- Environment made optional for implementations which determine the environment differently
- Changed BTDeployMgmtDB parameter to pickList to allow a variable to be used. Changed major version number to avoid a breaking change.
- Some errors changed to warnings.
- Check for deployed application on last server, on other servers only if the path exists.

### CODE REVIEW

**Comment by vercellone** [comment]
Looks good!  Disappointing that picklist is necessary to facilitate use of a variable, but it is a reasonable sacrifice.

There is one issue that I'd like addressed before merging.  InstallDir usage and help messages are inconsistent with that of Install's $Destination.  

1. Usage
  Install-BTDFApplication either uses $Destination unmodified, or defaults to (Join-Path $ProgramFiles $Name).  Deploy and Undeploy both unconditionally (Join-Path $InstallDir $Name).  All 3 should apply the same logic.  I think you have the right idea with the unconditional join.  That would allow the use of 1 root folder pipeline variable across all jobs/tasks if desired.  But, either way works for me as long as these 3 functions align.

2. HelpMessage
  Install-BTDFApplication's HelpMessage is currently:
> Path to the directory to which the product will be installed (optional; default is a subfolder by the same name as the product in `$env:ProgramFiles or `$env:ProgramFiles(x86))

  Please update all 3 to align with the chosen logic and appropriate verbiage to make it clear that they are optional and what the defaults will be.

**Comment by twinpiloot** [comment]
I fully agree with your feedback and aligned parameters and helptext. I kept the Destination optional though.

**Review by vercellone — APPROVED** [review]
$Destination changes are perfect!  I would have preferred a separate PR for the MgmtDb issue, but I'll allow it.

**Comment by vercellone** [comment]
Thanks again for the PR!

[v0.1.1](https://marketplace.visualstudio.com/items?itemName=vercellj.btdf-tasks) was just published to the marketplace.  Unfortunately, your PNGs are not visible in the overview.

Let me know if you have any questions, concerns, or suggestions.

**Comment by twinpiloot** [comment]
Thanks for your quick response and sorry I sneaked in a small change for an existing issue.

I wanted to test the final version, but noticed that one of the updated files was missing.
Don't know why, but I created a new pull request to fix this.

I also tried to fix the missing images.

Kind regards,

Martin

________________________________

**Pull request merged**
